# lab 3
OFILES = main.o fmenu.o fscan.o fsortera.o fgenerera.o fkalkylera.o fbinsok.o
CCFLAGS = -c -static -ansi
programlab3 : $(OFILES)
	gcc -o lab3 $(OFILES)

clean: $(OFILES)
	rm $(OFILES)
	rm lab3
